"use strict";
/* ============================================================
   EmpleaYa — app.js
   App local sin backend: empleos, postulaciones, favoritos y
   tema se guardan en localStorage del navegador.
   Grupos: 1)config 2)persistencia 3)navegación 4)búsqueda/
   filtros 5)listas 6)favoritos 7)postulaciones 8)CRUD
   reclutador 9)candidatos 10)respaldo 11)tema 12)modales.
   ============================================================ */

/* --- 1) Config: claves de localStorage, modales y paginación --- */
const K={jobs:"empleaya_jobs_v1",applications:"empleaya_applications_v1",favorites:"empleaya_favorites_v1"};
const THEME_KEY="empleaya_theme_v1";
const ALL_MODALS=["jobDetailModal","applicationModal","candidatesModal","confirmModal","successModal"];
const JOBS_PER_PAGE=5;
let jobsPage=1;
let lastFocused=null,pendingAction=null;
/* --- Datos de ejemplo: se cargan solo la primera vez --- */
const initialJobs=[
{id:"job_tech_001",title:"Desarrollador Frontend Junior",company:"Nova Digital",category:"Tecnología",modality:"Remoto",type:"Tiempo completo",location:"Argentina",salary:"$700.000 - $950.000",description:"Buscamos una persona con interés en desarrollo web para incorporarse a nuestro equipo. Participará en la creación y mantenimiento de interfaces web modernas y accesibles.",requirements:"• HTML, CSS y JavaScript.\n• Conocimientos básicos de Git.\n• Capacidad para trabajar en equipo.\n• Se valoran conocimientos de React.",benefits:"• Trabajo 100% remoto.\n• Capacitación continua.\n• Horario flexible.",contactEmail:"rrhh@novadigital.com",createdAt:"2026-09-10T10:00:00"},
{id:"job_admin_002",title:"Asistente Administrativo",company:"Grupo Horizonte",category:"Administración",modality:"Presencial",type:"Tiempo completo",location:"Resistencia, Chaco",salary:"$600.000 - $750.000",description:"Estamos buscando un asistente administrativo para colaborar con tareas de oficina, gestión documental, atención a proveedores y organización interna.",requirements:"• Secundario completo.\n• Manejo de Microsoft Office.\n• Buena comunicación.\n• Organización y responsabilidad.",benefits:"• Estabilidad laboral.\n• Obra social.\n• Capacitación interna.",contactEmail:"seleccion@grupohorizonte.com",createdAt:"2026-09-08T14:30:00"},
{id:"job_sales_003",title:"Asesor/a de Ventas",company:"Conecta Comercial",category:"Ventas",modality:"Híbrido",type:"Medio tiempo",location:"Corrientes, Argentina",salary:"$450.000 + comisiones",description:"Buscamos perfiles comerciales para asesorar clientes, detectar oportunidades y realizar seguimiento de ventas.",requirements:"• Experiencia en atención al cliente o ventas deseable.\n• Excelente comunicación.\n• Orientación a resultados.\n• Manejo básico de herramientas digitales.",benefits:"• Modalidad híbrida.\n• Comisiones por ventas.\n• Posibilidades de crecimiento.",contactEmail:"talento@conectacomercial.com",createdAt:"2026-09-06T09:15:00"},
{id:"job_design_004",title:"Diseñador/a Gráfico Freelance",company:"Estudio Prisma",category:"Diseño",modality:"Remoto",type:"Freelance",location:"Argentina",salary:"A convenir",description:"Buscamos diseñador/a gráfico para proyectos de identidad visual, piezas para redes sociales y material publicitario.",requirements:"• Manejo de herramientas de diseño.\n• Portfolio de trabajos.\n• Creatividad y atención al detalle.",benefits:"• Trabajo remoto.\n• Proyectos variados.\n• Horarios flexibles.",contactEmail:"hola@estudioprisma.com",createdAt:"2026-09-04T12:00:00"}];
let current=null,appJob=null,editingId=null,candidatesJobId=null;
/* --- 2) Persistencia: leer/guardar JSON en localStorage con manejo de errores --- */
function load(k,f){try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{toast("No se pudo guardar: almacenamiento lleno o bloqueado.","error");return false}}
function uid(p){return p+"_"+Date.now()+"_"+Math.random().toString(36).slice(2,8)}
function validEmail(e){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(e||"").trim())}
/* --- Arranque: si no hay datos, crea las 3 listas iniciales --- */
function init(){if(!Array.isArray(load(K.jobs,null)))save(K.jobs,initialJobs);if(!Array.isArray(load(K.applications,null)))save(K.applications,[]);if(!Array.isArray(load(K.favorites,null)))save(K.favorites,[])}
function jobs(){return load(K.jobs,[])}function apps(){return load(K.applications,[])}function favs(){return load(K.favorites,[])}
/* --- 3) Navegación: muestra una vista y oculta las otras dos --- */
function setNav(active){const on="px-4 py-2 rounded-lg text-sm font-semibold text-primary-700 bg-primary-50",off="px-4 py-2 rounded-lg text-sm font-semibold text-slate-600 hover:bg-slate-100";document.getElementById("navJobs").className=active==="jobs"?on:off;document.getElementById("navApps").className=active==="applications"?on:off;document.getElementById("navRecruiter").className=active==="recruiter"?on:off}
function switchView(v){document.getElementById("jobsView").classList.toggle("hidden",v!=="jobs");document.getElementById("applicationsView").classList.toggle("hidden",v!=="applications");document.getElementById("recruiterView").classList.toggle("hidden",v!=="recruiter");setNav(v);if(v==="recruiter"){renderRecruiterJobs()}if(v==="applications"){renderApplications()}if(v==="jobs"){renderJobs(true)}stats();window.scrollTo({top:0,behavior:"smooth"})}
function toggleMobileMenu(){const m=document.getElementById("mobileMenu"),b=document.getElementById("menuBtn"),open=m.classList.toggle("hidden");if(b)b.setAttribute("aria-expanded",String(!open))}
/* --- 4) Búsqueda y filtros: normaliza texto y lee los controles activos --- */
function norm(x){return String(x||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function modality(){return document.querySelector('input[name="modality"]:checked')?.value||""}
function selectedTypes(){const ids=["fullTimeFilter","partTimeFilter","contractFilter","freelanceFilter","internshipFilter"],out=[];ids.forEach(id=>{const el=document.getElementById(id);if(el&&el.checked)out.push(el.value)});return out}
function salaryNum(s){const m=String(s||"").replace(/\./g,"").match(/\d+/g);return m?Math.max(...m.map(Number)):0}
/* --- Aplica texto + categoría + modalidad + tipo + favoritos y ordena --- */
function getFilteredJobs(){let list=jobs();const q=norm(document.getElementById("searchInput").value.trim()),cat=document.getElementById("categoryFilter").value,mod=modality(),sort=document.getElementById("sortFilter").value,types=selectedTypes(),favOnly=document.getElementById("favOnlyFilter").checked,favList=favs();list=list.filter(j=>{const text=norm([j.title,j.company,j.category,j.modality,j.location,j.description,j.requirements].join(" "));return(!q||text.includes(q))&&(!cat||j.category===cat)&&(!mod||j.modality===mod)&&(!types.length||types.includes(j.type))&&(!favOnly||favList.includes(j.id))});if(sort==="recent")list.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(sort==="old")list.sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));if(sort==="salary")list.sort((a,b)=>salaryNum(b.salary)-salaryNum(a.salary));return list}
/* --- 5) Listas: pinta empleos con paginación de 5 + estados vacíos --- */
function renderJobs(reset){if(reset)jobsPage=1;const list=getFilteredJobs(),total=list.length,shown=Math.min(total,jobsPage*JOBS_PER_PAGE),page=list.slice(0,shown);document.getElementById("resultsCount").textContent=`${total} ${total===1?"oportunidad encontrada":"oportunidades encontradas"}`;const empty=total===0;document.getElementById("emptyState").classList.toggle("hidden",!empty);if(empty){const onlyFav=document.getElementById("favOnlyFilter").checked;document.getElementById("emptyTitle").textContent=onlyFav?"No tienes empleos guardados":"No encontramos empleos";document.getElementById("emptyText").textContent=onlyFav?"Tocá la estrella ☆ en una oferta para verla aquí.":"Probá con otros términos o quitá algunos filtros."}document.getElementById("jobsContainer").innerHTML=page.map(card).join("");const wrap=document.getElementById("loadMoreWrap");if(total>shown){wrap.classList.remove("hidden");document.getElementById("showingInfo").textContent=`Mostrando ${shown} de ${total}`;wrap.querySelector("button").textContent=`Mostrar más (${total-shown} restantes)`}else{wrap.classList.add("hidden")}updateBadges()}
function loadMoreJobs(){jobsPage++;renderJobs(false)}
/* --- Utilidades de presentación: iniciales, tiempo relativo y color por modalidad --- */
function initials(x){const a=String(x||"E").trim().split(/\s+/);return a.length>1?(a[0][0]+a[1][0]).toUpperCase():a[0].slice(0,2).toUpperCase()}
function rel(d){const x=Math.max(0,Date.now()-new Date(d)),m=Math.floor(x/60000),h=Math.floor(m/60),day=Math.floor(h/24);return m<60?"Hace unos minutos":h<24?`Hace ${h} ${h===1?"hora":"horas"}`:day<30?`Hace ${day} días`:new Date(d).toLocaleDateString("es-AR")}
function modClass(m){return m==="Remoto"?"bg-emerald-50 text-emerald-700 border-emerald-100":m==="Presencial"?"bg-amber-50 text-amber-700 border-amber-100":"bg-blue-50 text-blue-700 border-blue-100"}
function appsFor(jobId){return apps().filter(a=>a.jobId===jobId)}
/* --- Tarjeta de empleo con insignias de postulado/guardado --- */
function card(j){const f=favs().includes(j.id),applied=appsFor(j.id).length>0;return `<article class="job-card bg-white border border-slate-200 rounded-2xl p-5 sm:p-6 cursor-pointer" onclick="detail('${j.id}')"><div class="flex gap-4"><div class="w-12 h-12 sm:w-14 sm:h-14 shrink-0 rounded-xl bg-slate-100 flex items-center justify-center font-black text-primary-600">${esc(initials(j.company))}</div><div class="flex-1 min-w-0"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><h3 class="font-black text-lg text-slate-900 truncate">${esc(j.title)}</h3><p class="text-sm font-medium text-slate-500">${esc(j.company)}</p></div><button onclick="event.stopPropagation();favorite('${j.id}')" aria-label="Guardar en favoritos" class="w-9 h-9 rounded-lg hover:bg-slate-100 text-xl ${f?"text-amber-500":"text-slate-400"}">${f?"★":"☆"}</button></div><div class="flex flex-wrap gap-2 mt-4"><span class="px-2.5 py-1 rounded-lg text-xs font-bold bg-slate-100 text-slate-600">${esc(j.category)}</span><span class="px-2.5 py-1 rounded-lg text-xs font-bold border ${modClass(j.modality)}">${esc(j.modality)}</span><span class="px-2.5 py-1 rounded-lg text-xs font-bold bg-slate-100 text-slate-600">${esc(j.type)}</span>${applied?'<span class="px-2.5 py-1 rounded-lg text-xs font-bold bg-emerald-100 text-emerald-700">✓ Postulado</span>':""}${f?'<span class="px-2.5 py-1 rounded-lg text-xs font-bold bg-amber-100 text-amber-700">★ Guardado</span>':""}</div><div class="grid sm:grid-cols-2 gap-2 mt-4 text-sm text-slate-500"><span>📍 ${esc(j.location||"Ubicación no especificada")}</span><span>💰 ${esc(j.salary||"A convenir")}</span></div><p class="text-sm text-slate-600 mt-4 line-clamp-2">${esc(j.description)}</p><div class="mt-5 pt-4 border-t border-slate-100 flex items-center justify-between"><span class="text-xs text-slate-400">${rel(j.createdAt)}</span><span class="text-sm font-bold text-primary-600">Ver oferta →</span></div></div></div></article>`}
/* --- Detalle: rellena el modal y avisa si ya te postulaste --- */
function detail(id){const j=jobs().find(x=>x.id===id);if(!j)return;current=id;document.getElementById("detailIcon").textContent=initials(j.company);document.getElementById("detailTitle").textContent=j.title;document.getElementById("detailCompany").textContent=j.company;document.getElementById("detailMeta").innerHTML=[j.category,j.modality,j.type,j.location||"Ubicación no especificada",j.salary||"A convenir"].map((x,i)=>`<span class="px-3 py-1.5 rounded-lg ${i===1?modClass(j.modality):"bg-slate-100 text-slate-700"} text-sm font-semibold">${esc(x)}</span>`).join("");document.getElementById("detailDescription").textContent=j.description||"";document.getElementById("requirementsSection").classList.toggle("hidden",!j.requirements);document.getElementById("benefitsSection").classList.toggle("hidden",!j.benefits);document.getElementById("detailRequirements").textContent=j.requirements||"";document.getElementById("detailBenefits").textContent=j.benefits||"";const n=appsFor(id).length,note=document.getElementById("detailAppliedNote");if(n>0){note.classList.remove("hidden");note.textContent=`Ya tienes ${n} ${n===1?"postulación":"postulaciones"} en este navegador para este empleo. Puedes postularte de nuevo con otro email.`}else{note.classList.add("hidden");note.textContent=""}updateFav(id);document.getElementById("detailFavoriteButton").onclick=()=>{favorite(id);updateFav(id)};document.getElementById("detailApplyButton").onclick=()=>application(id);openModal("jobDetailModal")}
/* --- 6) Favoritos: guardar/quitar con estrella y filtro "solo guardados" --- */
function updateFav(id){const b=document.getElementById("detailFavoriteButton"),f=favs().includes(id);b.textContent=f?"★ Guardado":"☆ Guardar";b.className=f?"h-12 px-5 rounded-xl border border-amber-200 bg-amber-50 text-amber-700 font-semibold":"h-12 px-5 rounded-xl border border-slate-200 font-semibold"}
function favorite(id){let a=favs();if(a.includes(id)){a=a.filter(x=>x!==id);toast("Empleo eliminado de favoritos.","info")}else{a.push(id);toast("Empleo guardado en favoritos.","success")}save(K.favorites,a);renderJobs(false)}
function application(id){const j=jobs().find(x=>x.id===id);if(!j)return;appJob=id;document.getElementById("applicationJobName").textContent=`${j.title} · ${j.company}`;closeModal("jobDetailModal");openModal("applicationModal")}
/* --- 7) Postulaciones: valida, evita duplicados por email y refresca vistas --- */
function submitApplication(e){e.preventDefault();const btn=document.getElementById("submitAppBtn");btn.disabled=true;setTimeout(()=>btn.disabled=false,1500);const j=jobs().find(x=>x.id===appJob);if(!j)return;const name=document.getElementById("appName").value.trim(),email=document.getElementById("appEmail").value.trim(),phone=document.getElementById("appPhone").value.trim(),msg=document.getElementById("appMessage").value.trim();if(name.length<3){toast("Ingresá tu nombre completo (mín. 3 letras).","error");return}if(!validEmail(email)){toast("Ingresá un email válido.","error");return}if(phone&&phone.replace(/\D/g,"").length<6){toast("Ese teléfono parece incompleto.","error");return}const a={id:uid("application"),jobId:j.id,jobTitle:j.title,company:j.company,candidateName:name,candidateEmail:email,candidatePhone:phone,message:msg,createdAt:new Date().toISOString()},all=apps();if(all.some(x=>x.jobId===j.id&&norm(x.candidateEmail)===norm(email))){toast("Ya existe una postulación con ese email para este empleo.","info");return}all.push(a);if(save(K.applications,all)){document.getElementById("applicationForm").reset();updateCounts();closeModal("applicationModal");openModal("successModal");refreshAfterAppsChange()}}
function refreshAfterAppsChange(){renderJobs(false);renderApplications();renderRecruiterJobs();stats()}
function renderApplications(){const all=apps().slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));document.getElementById("appsCount").textContent=`${all.length} ${all.length===1?"postulación realizada":"postulaciones realizadas"}`;document.getElementById("appsEmptyState").classList.toggle("hidden",all.length>0);document.getElementById("applicationsContainer").innerHTML=all.map(a=>{const j=jobs().find(x=>x.id===a.jobId);return `<div class="bg-white border border-slate-200 rounded-2xl p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><h3 class="font-bold text-slate-900">${esc(a.jobTitle)} <span class="font-normal text-slate-500">· ${esc(a.company)}</span></h3><p class="text-sm text-slate-500 mt-1">${esc(a.candidateName)} · ${esc(a.candidateEmail)}${a.candidatePhone?" · "+esc(a.candidatePhone):""}</p>${a.message?`<p class="text-sm text-slate-600 mt-3 bg-slate-50 rounded-xl p-3 whitespace-pre-line">${esc(a.message)}</p>`:""}<p class="text-xs text-slate-400 mt-3">${rel(a.createdAt)}${!j?' · <span class="text-red-500 font-semibold">Esta oferta fue eliminada</span>':""}</p></div><button onclick="requestWithdraw('${a.id}')" class="shrink-0 px-3 py-2 rounded-lg text-sm font-semibold text-red-600 hover:bg-red-50 border border-red-100">Retirar</button></div><div class="mt-4 pt-4 border-t border-slate-100 flex gap-3">${j?`<button onclick="detail('${j.id}')" class="text-sm font-bold text-primary-600">Ver oferta →</button>`:""}</div></div>`}).join("")}
function doWithdraw(appId){save(K.applications,apps().filter(x=>x.id!==appId));toast("Postulación retirada.","info");refreshAfterAppsChange();if(!document.getElementById("candidatesModal").classList.contains("hidden"))renderCandidates()}
function withdrawApplication(appId){requestWithdraw(appId)}
/* --- 8) CRUD reclutador: publicar con validación o actualizar si se está editando --- */
function publishJob(e){e.preventDefault();const btn=document.getElementById("submitJobBtn");btn.disabled=true;setTimeout(()=>btn.disabled=false,1200);const g=id=>document.getElementById(id).value.trim(),title=g("jobTitle"),company=g("company"),category=document.getElementById("category").value,modalityV=document.getElementById("modality").value,type=document.getElementById("jobType").value,location=g("location")||"No especificada",salary=g("salary")||"A convenir",contactEmail=g("contactEmail"),description=g("description"),requirements=g("requirements"),benefits=g("benefits");if(title.length<4){toast("El título debe tener al menos 4 caracteres.","error");return}if(company.length<2){toast("Ingresá el nombre de la empresa.","error");return}if(!category||!modalityV||!type){toast("Elegí categoría, modalidad y tipo.","error");return}if(!validEmail(contactEmail)){toast("El email de contacto no es válido.","error");return}if(description.length<20){toast("La descripción debe tener al menos 20 caracteres.","error");return}const data={title,company,category,modality:modalityV,type,location,salary,contactEmail,description,requirements,benefits};if(editingId){const all=jobs(),ix=all.findIndex(x=>x.id===editingId);if(ix<0){toast("No se encontró el empleo a editar.","error");return}all[ix]={...all[ix],...data};if(save(K.jobs,all)){toast("Empleo actualizado correctamente.","success");cancelEdit();renderRecruiterJobs();renderJobs(false);stats()}}else{const j={id:uid("job"),...data,createdAt:new Date().toISOString()},a=jobs();a.push(j);if(save(K.jobs,a)){document.getElementById("jobForm").reset();updateCounts();toast("¡Empleo publicado correctamente!","success");renderRecruiterJobs();stats();setTimeout(()=>switchView("jobs"),500)}}}
/* --- Editar: carga el empleo en el formulario y cambia el botón a "Guardar" --- */
function editJob(id){const j=jobs().find(x=>x.id===id);if(!j)return;editingId=id;document.getElementById("jobTitle").value=j.title||"";document.getElementById("company").value=j.company||"";document.getElementById("category").value=j.category||"";document.getElementById("modality").value=j.modality||"";document.getElementById("jobType").value=j.type||"";document.getElementById("location").value=j.location==="No especificada"?"":(j.location||"");document.getElementById("salary").value=j.salary==="A convenir"?"":(j.salary||"");document.getElementById("contactEmail").value=j.contactEmail||"";document.getElementById("description").value=j.description||"";document.getElementById("requirements").value=j.requirements||"";document.getElementById("benefits").value=j.benefits||"";updateCounts();document.getElementById("formTitle").textContent="Editar oferta";document.getElementById("submitJobBtn").textContent="Guardar cambios";document.getElementById("cancelEditBtn").classList.remove("hidden");switchView("recruiter");document.getElementById("jobFormCard").scrollIntoView({behavior:"smooth"})}
function cancelEdit(){editingId=null;document.getElementById("jobForm").reset();updateCounts();document.getElementById("formTitle").textContent="Publicar una oferta";document.getElementById("submitJobBtn").textContent="Publicar empleo";document.getElementById("cancelEditBtn").classList.add("hidden")}

/* --- Panel admin: tarjetas con conteo de postulados y acceso a candidatos --- */
function renderRecruiterJobs(){const c=document.getElementById("recruiterJobsContainer"),a=jobs().slice().sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));c.innerHTML=a.length?a.map(j=>{const n=appsFor(j.id).length;return `<div class="bg-white border border-slate-200 rounded-2xl p-5"><div class="flex items-start justify-between gap-3"><div class="flex gap-3 min-w-0"><div class="w-11 h-11 shrink-0 rounded-xl bg-primary-50 text-primary-700 flex items-center justify-center font-black">${esc(initials(j.company))}</div><div class="min-w-0"><h3 class="font-bold text-slate-900 truncate">${esc(j.title)}</h3><p class="text-sm text-slate-500 truncate">${esc(j.company)}</p></div></div><div class="flex shrink-0 gap-1"><button onclick="editJob('${j.id}')" aria-label="Editar empleo" class="w-9 h-9 rounded-lg text-slate-500 hover:bg-slate-100">✏️</button><button onclick="requestDeleteJob('${j.id}')" aria-label="Eliminar empleo" class="w-9 h-9 rounded-lg text-red-500 hover:bg-red-50">🗑</button></div></div><div class="flex flex-wrap gap-2 mt-4"><span class="text-xs font-semibold px-2 py-1 rounded-lg bg-slate-100">${esc(j.category)}</span><span class="text-xs font-semibold px-2 py-1 rounded-lg border ${modClass(j.modality)}">${esc(j.modality)}</span><span class="text-xs font-semibold px-2 py-1 rounded-lg bg-slate-100">${esc(j.type)}</span><span class="text-xs font-semibold px-2 py-1 rounded-lg ${n>0?"bg-emerald-100 text-emerald-700":"bg-slate-100 text-slate-500"}">${n} ${n===1?"postulado":"postulados"}</span></div><p class="text-xs text-slate-500 mt-3 truncate">✉️ ${esc(j.contactEmail||"Sin email")}</p><div class="mt-4 pt-4 border-t border-slate-100 flex items-center justify-between"><span class="text-xs text-slate-400">${rel(j.createdAt)}</span><div class="flex gap-3"><button onclick="viewCandidates('${j.id}')" class="text-sm font-bold text-emerald-700">Candidatos (${n})</button><button onclick="detail('${j.id}')" class="text-sm font-bold text-primary-600">Ver →</button></div></div></div>`}).join(""):`<div class="md:col-span-2 xl:col-span-3 bg-white border border-slate-200 rounded-2xl p-8 text-center"><h3 class="font-bold text-lg">No hay empleos publicados</h3><p class="text-sm text-slate-500 mt-1">Publicá tu primera oferta.</p></div>`}
/* --- Confirmaciones con un solo modal (eliminar, retirar, ejemplos, borrar) --- */
function showConfirm(kind,id,title,text,btn,icon){pendingAction={kind,id};document.getElementById("confirmTitle").textContent=title;document.getElementById("confirmText").textContent=text;const b=document.getElementById("confirmBtn");b.textContent=btn;b.className=kind==="deleteJob"||kind==="wipe"?"flex-1 h-11 rounded-xl bg-red-600 hover:bg-red-700 text-white font-bold":"flex-1 h-11 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-bold";document.getElementById("confirmIcon").textContent=icon||"🗑";openModal("confirmModal")}
function requestDeleteJob(id){const j=jobs().find(x=>x.id===id);if(!j)return;showConfirm("deleteJob",id,"¿Eliminar empleo?",`Se eliminará "${j.title}" de ${j.company}. Esta acción no se puede deshacer.`,"Eliminar","🗑")}
function requestWithdraw(appId){const a=apps().find(x=>x.id===appId);if(!a)return;showConfirm("withdraw",appId,"¿Retirar postulación?",`Se retirará tu postulación a "${a.jobTitle}".`,"Retirar","📨")}
function requestReset(){showConfirm("reset",null,"¿Restablecer ejemplos?","Se reemplazarán los empleos por los 4 de ejemplo. Tus postulaciones y favoritos se mantienen.","Restablecer","↺")}
function requestWipe(){showConfirm("wipe",null,"¿Borrar todo?","Se borrarán empleos, postulaciones y favoritos de este navegador.","Borrar todo","⚠️")}
function confirmAction(){if(!pendingAction)return;const p=pendingAction;pendingAction=null;closeModal("confirmModal");if(p.kind==="deleteJob"){save(K.jobs,jobs().filter(x=>x.id!==p.id));save(K.favorites,favs().filter(x=>x!==p.id));if(editingId===p.id)cancelEdit();toast("Empleo eliminado correctamente.","success");renderRecruiterJobs();renderJobs(false);renderApplications();stats()}else if(p.kind==="withdraw"){doWithdraw(p.id)}else if(p.kind==="reset"){save(K.jobs,initialJobs);toast("Datos de ejemplo restablecidos.","success");renderJobs(true);renderRecruiterJobs();stats()}else if(p.kind==="wipe"){localStorage.removeItem(K.jobs);localStorage.removeItem(K.applications);localStorage.removeItem(K.favorites);init();cancelEdit();toast("Todo borrado. Se cargaron ejemplos limpios.","info");renderJobs(true);renderApplications();renderRecruiterJobs();stats()}}
function confirmDelete(){confirmAction()}
/* --- 9) Candidatos: ver quiénes se postularon a un empleo --- */
function viewCandidates(jobId){const j=jobs().find(x=>x.id===jobId);if(!j)return;candidatesJobId=jobId;renderCandidates();openModal("candidatesModal")}
function renderCandidates(){const j=jobs().find(x=>x.id===candidatesJobId);if(!j)return;const list=appsFor(j.id).slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));document.getElementById("candidatesJobName").textContent=`${j.title} · ${j.company} — ${list.length} ${list.length===1?"candidato":"candidatos"}`;document.getElementById("candidatesContainer").innerHTML=list.length?list.map(a=>`<div class="border border-slate-200 rounded-2xl p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-bold">${esc(a.candidateName)}</p><p class="text-sm text-slate-500">${esc(a.candidateEmail)}${a.candidatePhone?" · "+esc(a.candidatePhone):""}</p><p class="text-xs text-slate-400 mt-1">${rel(a.createdAt)}</p></div><button onclick="requestWithdraw('${a.id}')" class="text-xs font-semibold text-red-600 hover:bg-red-50 border border-red-100 rounded-lg px-3 py-2">Eliminar</button></div>${a.message?`<p class="text-sm text-slate-600 mt-3 bg-slate-50 rounded-xl p-3 whitespace-pre-line">${esc(a.message)}</p>`:""}<div class="flex gap-3 mt-3"><a href="mailto:${esc(a.candidateEmail)}" class="text-sm font-bold text-primary-600">Responder por email →</a></div></div>`).join(""):`<div class="text-center py-8"><div class="text-4xl mb-3">👥</div><h3 class="font-bold">Sin candidatos todavía</h3><p class="text-sm text-slate-500 mt-1">Cuando alguien se postule, aparecerá aquí.</p></div>`}
/* --- 10) Respaldo local: exportar a JSON e importar con validación --- */
function exportData(){const data={app:"EmpleaYa",version:1,exportedAt:new Date().toISOString(),jobs:jobs(),applications:apps(),favorites:favs()};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="empleaya_backup.json";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast("Copia exportada.","success")}
function importData(e){const f=e.target.files&&e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.jobs)||!Array.isArray(d.applications)||!Array.isArray(d.favorites))throw new Error("formato");const cleanJobs=d.jobs.filter(j=>j&&j.title&&j.company&&j.description).slice(0,500);if(!cleanJobs.length)throw new Error("vacio");save(K.jobs,cleanJobs);save(K.applications,d.applications.slice(0,2000));save(K.favorites,d.favorites.slice(0,1000));jobsPage=1;renderJobs(true);renderApplications();renderRecruiterJobs();stats();toast(`Importados ${cleanJobs.length} empleos.`,"success")}catch{toast("Archivo inválido. Debe ser un backup de EmpleaYa.","error")}e.target.value=""};r.readAsText(f)}
/* --- Contadores del panel, insignias y caracteres restantes en formularios --- */
function stats(){document.getElementById("totalJobsStat").textContent=jobs().length;document.getElementById("totalApplicationsStat").textContent=apps().length;updateBadges()}
function updateBadges(){const nApps=apps().length,badge=document.getElementById("navAppsBadge");if(badge){badge.textContent=nApps;badge.classList.toggle("hidden",nApps===0)}const favLabel=document.getElementById("favCountLabel");if(favLabel)favLabel.textContent=`(${favs().length})`}
function isDark(){return document.documentElement.classList.contains("dark")}
/* --- 11) Tema: aplica claro/oscuro, lo recuerda y actualiza el botón 🌙/☀️ --- */
function applyTheme(t){document.documentElement.classList.toggle("dark",t==="dark");try{localStorage.setItem(THEME_KEY,t)}catch(e){}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute("content",t==="dark"?"#0f172a":"#1243b0");document.querySelectorAll(".themeBtn").forEach(b=>{b.textContent=t==="dark"?"☀️":"🌙";b.setAttribute("aria-label",t==="dark"?"Cambiar a modo claro":"Cambiar a modo oscuro")})}
function initTheme(){let t="light";try{t=localStorage.getItem(THEME_KEY)||(window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light")}catch(e){}applyTheme(t)}
function toggleTheme(){applyTheme(isDark()?"light":"dark")}
function updateCounts(){const s=(id,out,max)=>{const el=document.getElementById(id),o=document.getElementById(out);if(el&&o)o.textContent=(el.value||"").length};s("description","descCount");s("requirements","reqCount");s("benefits","benCount");s("appMessage","msgCount")}
function clearFilters(){document.getElementById("searchInput").value="";document.getElementById("categoryFilter").value="";document.getElementById("sortFilter").value="recent";["fullTimeFilter","partTimeFilter","contractFilter","freelanceFilter","internshipFilter"].forEach(id=>{document.getElementById(id).checked=false});document.getElementById("favOnlyFilter").checked=false;document.querySelectorAll('input[name="modality"]').forEach(x=>x.checked=x.value==="");renderJobs(true)}
/* --- 12) Modales, avisos y seguridad: foco accesible, escape y anti-XSS --- */
function anyModalOpen(){return ALL_MODALS.some(id=>!document.getElementById(id).classList.contains("hidden"))}
function topModal(){for(let i=ALL_MODALS.length-1;i>=0;i--){const m=document.getElementById(ALL_MODALS[i]);if(!m.classList.contains("hidden"))return m}return null}
function openModal(id){lastFocused=document.activeElement;document.getElementById(id).classList.remove("hidden");document.getElementById(id).classList.add("flex");document.body.classList.add("overflow-hidden");setTimeout(()=>{const m=document.getElementById(id),f=m.querySelector("input,select,textarea,button");if(f)f.focus({preventScroll:true})},50)}
function closeModal(id){document.getElementById(id).classList.add("hidden");document.getElementById(id).classList.remove("flex");if(!anyModalOpen()){document.body.classList.remove("overflow-hidden");if(lastFocused&&lastFocused.focus)lastFocused.focus({preventScroll:true})}}
function toast(msg,type){type=type||"success";const c=document.getElementById("toastContainer"),d=document.createElement("div");let icon="✓",box="bg-emerald-100 text-emerald-700";if(type==="error"){icon="!";box="bg-red-100 text-red-700"}else if(type==="info"){icon="i";box="bg-blue-100 text-blue-700"}d.className="toast bg-white border border-slate-200 shadow-xl rounded-xl p-4 flex items-center gap-3";const s=document.createElement("span");s.className=`w-8 h-8 shrink-0 rounded-full ${box} flex items-center justify-center font-black`;s.textContent=icon;const t=document.createElement("span");t.className="text-sm font-semibold";t.textContent=msg;d.appendChild(s);d.appendChild(t);c.appendChild(d);setTimeout(()=>{d.remove()},3200)}
function esc(x){return String(x??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
/* --- Eventos globales: clic fuera cierra, "/" busca, Tab no escapa del modal --- */
document.addEventListener("click",e=>{ALL_MODALS.forEach(id=>{const m=document.getElementById(id);if(!m.classList.contains("hidden")&&e.target===m)closeModal(id)})});
document.addEventListener("keydown",e=>{if(e.key==="Escape")ALL_MODALS.forEach(id=>{if(!document.getElementById(id).classList.contains("hidden"))closeModal(id)});if(e.key==="/"&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();switchView("jobs");setTimeout(()=>document.getElementById("searchInput").focus(),100)}if(e.key==="Tab"){const m=topModal();if(m){const f=[...m.querySelectorAll("button,input,select,textarea,a[href]")].filter(el=>!el.disabled&&el.offsetParent!==null);if(f.length){const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}});
/* --- Arranque de la app + sincronización entre pestañas + menú móvil --- */
document.addEventListener("DOMContentLoaded",()=>{init();initTheme();renderJobs(true);renderApplications();renderRecruiterJobs();stats();updateCounts()});window.addEventListener("storage",()=>{renderJobs(false);renderApplications();renderRecruiterJobs();stats()});
window.addEventListener("resize",()=>{if(window.innerWidth>=768)document.getElementById("mobileMenu").classList.add("hidden")});
